### ISSUE TITLE
[Suggestion] configurable size for caves

### ISSUE THREAD

**Issue by Biviho** [Fuzss/swisscheese#1]
i don't know if you are interested in continue developing this awesome mod, but in that case i have a suggestion:
make cave size configurable in the config (something like quark experimental cave) to have better costumization.
i tested the mod with other cavegen mods and most of them will not work...so it would be great to have more costumization provided by the mod

**Comment by Fuzss** [comment]
Sure, that'd be simple to implement if I ever come back to this.

About other cave gen mods not working; that's no surprise. This mod completely replaces the vanilla cave generation system, so other mods hocking into the vanilla system or providing their own replacement technically won't even load.

**Comment by Biviho** [comment]
that would be geat!

for what i know there is only one that can work with your generation: "cave generator"
i used it to generate some decorated big chambers, but i didn't find a way to not generate them under oceans...as a result it didn't work well with underwater cave as it generate floating water in that big chambers under oceans.

**Comment by Fuzss** [comment]
Mod is discontinued now.
